# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Nextcloud installation tasks
  block:
    - name: Validate Nextcloud configuration
      when: nextcloud_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Nextcloud
      when: nextcloud_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-nextcloud
    - install-all
    - install-nextcloud

- name: Perform Nextcloud configuration adjustment tasks
  block:
    - name: Adjust Nextcloud configuration
      when: nextcloud_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/adjust_config.yml"
  tags:
    - adjust-nextcloud-config

- name: Perform tasks to print database credentials for Nextcloud
  block:
    - name: Print database credentials for Nextcloud
      when: nextcloud_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/print_db_credentials.yml"
  tags:
    - print-nextcloud-db-credentials

- name: Perform Collabora Online Development Edition installation tasks for Nextcloud
  block:
    - name: Install Collabola Online as Office application on Nextcloud
      when: nextcloud_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/app_install_collabora.yml"
  tags:
    - install-nextcloud-app-collabora

- name: Perform Nextcloud uninstallation tasks
  block:
    - name: Uninstall Nextcloud
      when: not nextcloud_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-nextcloud
