# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Nextcloud systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ nextcloud_identifier }}-server.service"
  register: nextcloud_service_stat

- when: nextcloud_service_stat.stat.exists | bool
  block:
    - name: Ensure Nextcloud systemd services are stopped
      when: item.when | bool
      ansible.builtin.service:
        name: "{{ nextcloud_identifier }}-{{ item.service }}"
        state: stopped
        enabled: false
        daemon_reload: true
      with_items:
        - {'service': server.service, 'when': true}
        - {'service': cron.service, 'when': true}
        - {'service': cron.timer, 'when': true}
        - {'service': app-update.service, 'when': "{{ nextcloud_auto_app_update_enabled }}"}
        - {'service': app-update.timer, 'when': "{{ nextcloud_auto_app_update_enabled }}"}

    - name: Ensure Nextcloud systemd services do not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ nextcloud_identifier }}-{{ item }}"
        state: absent
      with_items:
        - server.service
        - cron.service
        - cron.timer
        - app-update.service
        - app-update.timer

    - name: Ensure Nextcloud container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ nextcloud_container_network }}"
        state: absent

    - name: Ensure Nextcloud container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ nextcloud_container_network }}
      register: network_deletion_result
      changed_when: nextcloud_container_network in network_deletion_result.stdout

    - name: Ensure Nextcloud path does not exist
      ansible.builtin.file:
        path: "{{ nextcloud_base_path }}"
        state: absent
