# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Nextcloud systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ nextcloud_identifier }}-server.service"
  register: nextcloud_service_stat

- when: nextcloud_service_stat.stat.exists | bool
  block:
    - name: Ensure Nextcloud systemd services are stopped
      when: item.when | bool
      ansible.builtin.service:
        name: "{{ nextcloud_identifier }}-{{ item.service }}"
        state: stopped
        enabled: false
        daemon_reload: true
      with_items:
        - {'service': server.service, 'when': true}
        - {'service': cron.service, 'when': true}
        - {'service': cron.timer, 'when': true}
        - {'service': app-update.service, 'when': "{{ nextcloud_auto_app_update_enabled }}"}
        - {'service': app-update.timer, 'when': "{{ nextcloud_auto_app_update_enabled }}"}

    - name: Ensure Nextcloud systemd services do not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ nextcloud_identifier }}-{{ item }}"
        state: absent
      with_items:
        - server.service
        - cron.service
        - cron.timer
        - app-update.service
        - app-update.timer

    - name: Ensure Nextcloud path does not exist
      ansible.builtin.file:
        path: "{{ nextcloud_base_path }}"
        state: absent
