# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Gergely Horváth
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "nextcloud_container_additional_mounts", "new": "nextcloud_container_additional_volumes" }
    - { "old": "nextcloud_preview_squareSizes", "new": "<removed>" }
    - { "old": "nextcloud_preview_widthSizes", "new": "<removed>" }
    - { "old": "nextcloud_preview_heightSizes", "new": "<removed>" }
    - { "old": "nextcloud_preview_system_jpeg_quality", "new": "<removed>" }
    - "old": "nextcloud_container_image_customizations_php_imageick_installation_enabled"
      "new": "nextcloud_container_image_customizations_php_imagick_installation_enabled"
    - "old": "nextcloud_container_image_customizations_php_imageick_installation_package"
      "new": "nextcloud_container_image_customizations_php_imagick_installation_packages"
    - { "old": "nextcloud_container_additional_environment_variables", "new": "nextcloud_environment_variables_additional_variables" }
    - { "old": "nextcloud_config_default_parameters", "new": "nextcloud_config_parameters_default" }
    - { "old": "nextcloud_config_additional_parameters", "new": "nextcloud_config_parameters_custom" }

- name: Fail if required Nextcloud settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.name), wantlist=True) | length == 0"
  with_items:
    - { "name": "nextcloud_hostname", when: true }
    - { "name": "nextcloud_uid", when: true }
    - { "name": "nextcloud_gid", when: true }
    - { "name": "nextcloud_database_hostname", when: true }
    - { "name": "nextcloud_database_password", when: true }
    - "name": "nextcloud_container_labels_traefik_compression_middleware_name"
      when: "{{ nextcloud_container_labels_traefik_compression_middleware_enabled }}"

- name: Fail if Nextcloud database type is invalid
  ansible.builtin.fail:
    msg: >-
      nextcloud_database_type must be 'mysql', 'postgres' or 'sqlite'
  when: "nextcloud_database_type not in ['mysql', 'postgres', 'sqlite']"

- name: Fail if required Nextcloud + MySQL integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `nextcloud_database_type` is `mysql`
  when: "nextcloud_database_type == 'mysql' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - nextcloud_database_mysql_hostname
    - nextcloud_database_mysql_password

- name: Fail if required Nextcloud + Postgres integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `nextcloud_database_type` is `postgres`
  when: "nextcloud_database_type == 'postgres' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - nextcloud_database_hostname
    - nextcloud_database_password

- name: Fail if SMTP settings are missing (and SMTP is enabled by setting host)
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) to correctly set up email via SMTP.
  when: "nextcloud_config_parameter_mail_smtphost != '' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - nextcloud_config_parameter_mail_smtpport
    - nextcloud_config_parameter_mail_from_address
    - nextcloud_config_parameter_mail_domain

- name: Run if Traefik is enabled
  when: nextcloud_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Nextcloud are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - nextcloud_container_labels_traefik_hostname
        - nextcloud_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `nextcloud_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if nextcloud_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          nextcloud_container_labels_traefik_path_prefix (`{{ nextcloud_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/nextcloud`).
      when: "nextcloud_container_labels_traefik_path_prefix != '/' and nextcloud_container_labels_traefik_path_prefix[-1] == '/'"
